## Matrix Arithmetic

In [1]:
import numpy as np

In [2]:
x=np.matrix([[1, 2], [3, 4]])

y=np.matrix([[5, 3], [8, 7]])
#Numpy matrices are strictly 2-dimensional, while numpy arrays (ndarrays) are N-dimensional. 
#provide a convenient notation for matrix multiplication

In [3]:
print(type(y))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [4]:
print(x)

[[1 2]
 [3 4]]


In [5]:
print(x+y)

[[ 6  5]
 [11 11]]


In [6]:
print(x*3)

[[ 3  6]
 [ 9 12]]


## Subtraction

In [7]:
print(x-y)

[[-4 -1]
 [-5 -3]]


## Multiplication

In [8]:
A=np.matrix([[1, 2], [3, 4]])

print(A)

[[1 2]
 [3 4]]


In [9]:
#haddmard multiplication
print (A*A)

[[ 7 10]
 [15 22]]


In [10]:
#elemant wise multiplication
print(np.multiply(A,A))

[[ 1  4]
 [ 9 16]]


## Inverse

In [11]:
from numpy.linalg import inv

In [12]:
print(inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


## Transpose

In [13]:
print(A.T) #flip rows with columns 

[[1 3]
 [2 4]]
