## Basic Numpy Operations

In [1]:
import numpy as np

In [2]:
a=[1,2,11,6,8,18,2]

na=np.array(a)

print(type(na))

<type 'numpy.ndarray'>


In [3]:
print(na.shape) #its a rank 1 numpy array with 7 items

(7L,)


In [4]:
#lets print out an elemant at index 2
print(na[2])

11


In [5]:
#isolate an entire chunk based on start index-end index
#print out values at start to end-1 index location

print(na[1:5])

[ 2 11  6  8]


In [6]:
#use a step of two

print(na[1:5:2])

[2 6]


In [7]:
#negative index
#print out values at start to end+1 index location

print(a[-7:-3]) #will isolate numbers till -4

[1, 2, 11, 6]


In [8]:
#print last item
print(a[-1])

2


In [9]:
#items start at one index and all the way to the end

print(a[3:])

[6, 8, 18, 2]


In [10]:
#print items from begining through end-1

print(a[:4])

[1, 2, 11, 6]


In [11]:
b=a[:] #copy an array
print(b)

[1, 2, 11, 6, 8, 18, 2]


In [12]:
#concatenate two numpy arrays

x=np.array([2,6,8,4])

y=np.array([11,8,2])

z=np.concatenate([x,y])

print(z)

[ 2  6  8  4 11  8  2]


#### Multi-dimensional array operations

In [13]:
arr=[[1,2,3,4],[3,4,5,6],[7,8,9,6],[12,7,10,9],[2,11,8,10]]

narr=np.array(arr) #convert array into numpy array

print (narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9  6]
 [12  7 10  9]
 [ 2 11  8 10]]


In [14]:
print(narr[0]) #print first row at row index 0

[1 2 3 4]


In [15]:
print(narr[2]) #print 3rd row, at row index 2

[7 8 9 6]


In [16]:
print(narr[2,3]) #print contents of row with index 0 and column with index 1 [row,columm]

6


In [17]:
narr[3,0]=14 #replace value at a location

print(narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9  6]
 [14  7 10  9]
 [ 2 11  8 10]]


In [18]:
#get the last row
print(narr[-1])

[ 2 11  8 10]


In [19]:
#get the 2nd last
print(narr[-2])

[14  7 10  9]


In [20]:
# print rows and columns

print(narr[1:4,2:5]) #rows: 1 to 4-1 and columns 2 to 5-1

[[ 5  6]
 [ 9  6]
 [10  9]]


In [21]:
###concatenation row and column wise

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

#concatenate row wise 

c=np.concatenate((a, b))

print(c)

[[1 2]
 [3 4]
 [5 6]]
