In [1]:
import numpy as np

In [3]:
import torch 

In [7]:
array = [[1,2,3],[4,5,6]]
first_array = np.array(array) # 2x3 array
print("Array Type: {}".format(type(first_array))) # type
print("Array Shape: {}".format(np.shape(first_array))) # shape
print(first_array)

Array Type: <class 'numpy.ndarray'>
Array Shape: (2, 3)
[[1 2 3]
 [4 5 6]]


### convert numpy array to tensor

In [8]:
# pytorch array
tensor = torch.Tensor(array)
print("Array Type: {}".format(tensor.type)) # type
print("Array Shape: {}".format(tensor.shape)) # shape
print(tensor)

Array Type: <built-in method type of Tensor object at 0x11fa771f8>
Array Shape: torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Ones matrix

In [9]:
print("Numpy {}\n".format(np.ones((3,3))))

# pytorch ones
print(torch.ones((3,3)))

Numpy [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


### random numbers

In [10]:
print("Numpy {}\n".format(np.random.rand(3,3)))

# pytorch random
print(torch.rand(3,3))

Numpy [[0.00685806 0.72035226 0.72365844]
 [0.72604927 0.25398466 0.78610103]
 [0.20600558 0.36670855 0.62552722]]

tensor([[0.9642, 0.8427, 0.0597],
        [0.9828, 0.0710, 0.9295],
        [0.1090, 0.4654, 0.7514]])


### to & fro conversions

In [11]:
array = np.random.rand(3,2)
print("{} {}\n".format(type(array),array))



<class 'numpy.ndarray'> [[0.21571444 0.21642089]
 [0.06103213 0.1951619 ]
 [0.97528898 0.36627427]]



In [12]:
# from numpy to tensor
from_numpy_to_tensor = torch.from_numpy(array)
print("{}\n".format(from_numpy_to_tensor))



tensor([[0.2157, 0.2164],
        [0.0610, 0.1952],
        [0.9753, 0.3663]], dtype=torch.float64)



In [13]:
# from tensor to numpy
tensor = from_numpy_to_tensor
from_tensor_to_numpy = tensor.numpy()
print("{} {}\n".format(type(from_tensor_to_numpy),from_tensor_to_numpy))

<class 'numpy.ndarray'> [[0.21571444 0.21642089]
 [0.06103213 0.1951619 ]
 [0.97528898 0.36627427]]



In [14]:
import torch      
from torch.autograd import Variable     
import torch.nn as nn 
import warnings

In [15]:
import torchvision

In [ ]:
##http://howieko.com/projects/classifying_flowers_pytorch/
##https://www.kaggle.com/aradhyamathur/flower-classification-pytorch
##https://katba-caroline.com/what-flower-is-this-developing-an-image-classifier-with-deep-learning-using-pytorch/

In [ ]:
#https://medium.com/datadriveninvestor/creating-a-pytorch-image-classifier-da9db139ba80