## Vector Arithmetic

In [1]:
import numpy as np

In [2]:
#create numpy arrays
x = np.array([1,2,3])
y = np.array([2,3,4])

### addition

In [3]:
print(x+y)

[3 5 7]


In [4]:
#scalar addition
print(x+2)

[3 4 5]


### subtract

In [5]:
print(y-x)

[1 1 1]


### multiply

In [6]:
#hadmard product

print(x*y)

[ 2  6 12]


In [7]:
#dot product
print(np.dot(y,x))

20


In [8]:
print(y/x)

[2 1 1]
